language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script:
  - composer install --no-interaction --prefer-source
  - composer require --dev phpunit/phpunit

script:
  - ./vendor/bin/phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
